# Generated by Django 5.2 on 2025-11-03 14:19

import django.db.models.deletion
import individuals.numbers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individuals', '0002_alter_department_and_territory_char_lengths'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='external_order_number',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='External order number'),
        ),
        migrations.AddField(
            model_name='individual',
            name='import_reference',
            field=models.CharField(blank=True, help_text='a reference number in an external data source', max_length=64, null=True, verbose_name='import reference'),
        ),
        migrations.AddField(
            model_name='individual',
            name='species_checked_date',
            field=models.DateField(blank=True, null=True, verbose_name='categorized at'),
        ),
        migrations.AddField(
            model_name='individual',
            name='status',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='individual',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individuals', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='outplanting',
            name='comment',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='accession_number',
            field=models.CharField(db_index=True, default=individuals.numbers.get_new_accession_number, max_length=30, null=True, unique=True, verbose_name='accession #'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='came_in_as',
            field=models.CharField(blank=True, choices=[('PF', 'Plant'), ('PT', 'Plant part'), ('SA', 'Seed'), ('SÄ', 'Seedling'), ('ST', 'Scion'), ('SP', 'Spores'), ('UN', 'unknown')], db_index=True, max_length=2, verbose_name='received as'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='order_number',
            field=models.CharField(default=individuals.numbers.get_new_order_number, max_length=20, unique=True, verbose_name='order number'),
        ),
    ]
