# Generated by Django 5.2 on 2025-10-13 13:02

import individuals.numbers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individuals', '0002_alter_department_and_territory_char_lengths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='accession_number',
            field=models.CharField(db_index=True, default=individuals.numbers.get_new_accession_number, max_length=20, null=True, unique=True, verbose_name='accession #'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='order_number',
            field=models.CharField(default=individuals.numbers.get_new_order_number, max_length=20, unique=True, verbose_name='order number'),
        ),
    ]
