# Generated by Django 5.2 on 2025-10-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individuals', '0003_individual_accession_number_as_char'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='external_order_number',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='External order number'),
        ),
    ]
