# Generated by Django 5.2 on 2026-01-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individuals', '0003_add_and_alter_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='has_specimen_generated',
            field=models.BooleanField(default=False, editable=False, verbose_name='has specimen'),
        ),
    ]
