# Generated by Django 5.2 on 2026-06-04 10:19

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('individuals', '0004_individual_has_specimen_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='polygon',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, geography=True, null=True, srid=4326, verbose_name='polygon'),
        ),
        migrations.AddField(
            model_name='outplanting',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, db_index=True, geography=True, null=True, srid=4326, verbose_name='location'),
        ),
        migrations.AddField(
            model_name='territory',
            name='polygon',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, geography=True, null=True, srid=4326, verbose_name='polygon'),
        ),
    ]
