# Generated by Django 5.2 on 2026-07-22 10:57

import config_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0004_customprops'),
        ('individuals', '0005_geo_coords'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='custom_values_bool',
            field=config_app.fields.CustomPropertyValuesBoolField(related_name='department_values_bool', to='config_app.propertyvaluebool', verbose_name='bool values'),
        ),
        migrations.AddField(
            model_name='department',
            name='custom_values_text',
            field=config_app.fields.CustomPropertyValuesTextField(related_name='department_values_text', to='config_app.propertyvaluetext', verbose_name='text values'),
        ),
        migrations.AddField(
            model_name='individual',
            name='custom_values_bool',
            field=config_app.fields.CustomPropertyValuesBoolField(related_name='individual_values_bool', to='config_app.propertyvaluebool', verbose_name='bool values'),
        ),
        migrations.AddField(
            model_name='individual',
            name='custom_values_text',
            field=config_app.fields.CustomPropertyValuesTextField(related_name='individual_values_text', to='config_app.propertyvaluetext', verbose_name='text values'),
        ),
        migrations.AddField(
            model_name='territory',
            name='custom_values_bool',
            field=config_app.fields.CustomPropertyValuesBoolField(related_name='territory_values_bool', to='config_app.propertyvaluebool', verbose_name='bool values'),
        ),
        migrations.AddField(
            model_name='territory',
            name='custom_values_text',
            field=config_app.fields.CustomPropertyValuesTextField(related_name='territory_values_text', to='config_app.propertyvaluetext', verbose_name='text values'),
        ),
    ]
