# Generated by Django 5.2 on 2026-07-22 10:57

from django.db import migrations, models
from django.conf import settings
import config_app.fields
import tools.global_request


def clear_creation_fields(apps, schema_editor):
    for Model in (
            apps.get_model('individuals', 'Territory'),
            apps.get_model('individuals', 'Department'),
            apps.get_model('individuals', 'Individual'),
            apps.get_model('individuals', 'Outplanting'),
    ):
        Model.objects.all().update(created_date=None, modified_date=None)


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0004_customprops'),
        ('individuals', '0005_geo_coords'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='custom_values_bool',
            field=config_app.fields.CustomPropertyValuesBoolField(related_name='department_values_bool', to='config_app.propertyvaluebool', verbose_name='bool values'),
        ),
        migrations.AddField(
            model_name='department',
            name='custom_values_text',
            field=config_app.fields.CustomPropertyValuesTextField(related_name='department_values_text', to='config_app.propertyvaluetext', verbose_name='text values'),
        ),
        migrations.AddField(
            model_name='department',
            name='custom_values_user',
            field=config_app.fields.CustomPropertyValuesUserField(related_name='department_values_user', to='config_app.propertyvalueuser', verbose_name='user values'),
        ),
        migrations.AddField(
            model_name='department',
            name='created_by',
            field=models.ForeignKey(null=True, blank=True, on_delete=models.deletion.CASCADE, related_name='department_created_users', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='department',
            name='created_date',
            field=models.DateField(null=True, blank=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='department',
            name='modified_by',
            field=models.ForeignKey(null=True, blank=True, on_delete=models.deletion.CASCADE, related_name='department_modified_users', to=settings.AUTH_USER_MODEL, verbose_name='modified by'),
        ),
        migrations.AddField(
            model_name='department',
            name='modified_date',
            field=models.DateField(null=True, blank=True, verbose_name='modified at'),
        ),

        migrations.AddField(
            model_name='individual',
            name='custom_values_bool',
            field=config_app.fields.CustomPropertyValuesBoolField(related_name='individual_values_bool', to='config_app.propertyvaluebool', verbose_name='bool values'),
        ),
        migrations.AddField(
            model_name='individual',
            name='custom_values_text',
            field=config_app.fields.CustomPropertyValuesTextField(related_name='individual_values_text', to='config_app.propertyvaluetext', verbose_name='text values'),
        ),
        migrations.AddField(
            model_name='individual',
            name='custom_values_user',
            field=config_app.fields.CustomPropertyValuesUserField(related_name='individual_values_user', to='config_app.propertyvalueuser', verbose_name='user values'),
        ),
        migrations.AddField(
            model_name='individual',
            name='created_by',
            field=models.ForeignKey(null=True, blank=True, on_delete=models.deletion.CASCADE, related_name='individual_created_users', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='individual',
            name='created_date',
            field=models.DateField(null=True, blank=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='individual',
            name='modified_by',
            field=models.ForeignKey(null=True, blank=True, on_delete=models.deletion.CASCADE, related_name='individual_modified_users', to=settings.AUTH_USER_MODEL, verbose_name='modified by'),
        ),
        migrations.AddField(
            model_name='individual',
            name='modified_date',
            field=models.DateField(null=True, blank=True, verbose_name='modified at'),
        ),

        migrations.AddField(
            model_name='outplanting',
            name='created_by',
            field=models.ForeignKey(null=True, blank=True, on_delete=models.deletion.CASCADE, related_name='outplanting_created_users', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='outplanting',
            name='created_date',
            field=models.DateField(null=True, blank=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='outplanting',
            name='modified_by',
            field=models.ForeignKey(null=True, blank=True, on_delete=models.deletion.CASCADE, related_name='outplanting_modified_users', to=settings.AUTH_USER_MODEL, verbose_name='modified by'),
        ),
        migrations.AddField(
            model_name='outplanting',
            name='modified_date',
            field=models.DateField(null=True, blank=True, verbose_name='modified at'),
        ),

        migrations.AddField(
            model_name='territory',
            name='custom_values_bool',
            field=config_app.fields.CustomPropertyValuesBoolField(related_name='territory_values_bool', to='config_app.propertyvaluebool', verbose_name='bool values'),
        ),
        migrations.AddField(
            model_name='territory',
            name='custom_values_text',
            field=config_app.fields.CustomPropertyValuesTextField(related_name='territory_values_text', to='config_app.propertyvaluetext', verbose_name='text values'),
        ),
        migrations.AddField(
            model_name='territory',
            name='custom_values_user',
            field=config_app.fields.CustomPropertyValuesUserField(related_name='territory_values_user', to='config_app.propertyvalueuser', verbose_name='user values'),
        ),
        migrations.AddField(
            model_name='territory',
            name='created_by',
            field=models.ForeignKey(null=True, blank=True, on_delete=models.deletion.CASCADE, related_name='territory_created_users', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='territory',
            name='created_date',
            field=models.DateField(null=True, blank=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='territory',
            name='modified_by',
            field=models.ForeignKey(null=True, blank=True, on_delete=models.deletion.CASCADE, related_name='territory_modified_users', to=settings.AUTH_USER_MODEL, verbose_name='modified by'),
        ),
        migrations.AddField(
            model_name='territory',
            name='modified_date',
            field=models.DateField(null=True, blank=True, verbose_name='modified at'),
        ),

        migrations.RunPython(clear_creation_fields, migrations.RunPython.noop),
    ]
