# Generated by Django 5.2 on 2026-06-02 09:04

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('individuals', '0005_geo_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='territory',
            name='polygon',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, geography=True, null=True, srid=4326, verbose_name='polygon'),
        ),
    ]
