# Generated by Django 5.2 on 2026-07-17 09:22

import individuals.numbers
from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('individuals', '0006_customprops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='accession_number',
            field=models.CharField(
                db_collation='natural_sort' if settings.IS_POSTGRES else None,
                db_index=True, default=individuals.numbers.get_new_accession_number, max_length=30, null=True, unique=True, verbose_name='accession #',
            ),
        ),
        migrations.AlterField(
            model_name='individual',
            name='collector_number',
            field=models.CharField(
                db_collation='natural_sort' if settings.IS_POSTGRES else None,
                blank=True, max_length=100, verbose_name='collection number',
            ),
        ),
        migrations.AlterField(
            model_name='individual',
            name='id_name_generated',
            field=models.CharField(
                db_collation='natural_sort' if settings.IS_POSTGRES else None,
                default='', editable=False, max_length=100, verbose_name='name',
            ),
        ),
        migrations.AlterField(
            model_name='individual',
            name='order_number',
            field=models.CharField(
                db_collation='natural_sort' if settings.IS_POSTGRES else None,
                default=individuals.numbers.get_new_order_number, max_length=20, unique=True, verbose_name='order number',
            ),
        ),
        migrations.AlterField(
            model_name='individual',
            name='sowing_number',
            field=models.CharField(
                db_collation='natural_sort' if settings.IS_POSTGRES else None,
                blank=True, max_length=100, verbose_name='sowing number',
            ),
        ),
    ]
