# Generated by Django 5.2 on 2026-08-04 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individuals', '0007_individual_natural_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='species_audit',
            field=models.JSONField(null=True, verbose_name='Species audit'),
        ),
    ]
