# Generated by Django 5.2 on 2026-08-06 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individuals', '0007_individual_natural_sort'),
        ('literature', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='species_audit',
            field=models.JSONField(blank=True, null=True, verbose_name='Determination audit'),
        ),
        migrations.AddField(
            model_name='individual',
            name='literature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individuals', to='literature.literature', verbose_name='literature'),
        ),
        migrations.AlterField(
            model_name='outplanting',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
    ]
