# Generated by Django 5.2 on 2026-08-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individuals', '0007_individual_natural_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='species_audit',
            field=models.JSONField(blank=True, null=True, verbose_name='Determination audit'),
        ),
        migrations.AlterField(
            model_name='outplanting',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
    ]
