# Generated by Django 5.2 on 2026-09-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individuals', '0008_individual_species_audit'),
        ('meta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='individuals', to='meta.project', verbose_name='project assignment'),
        ),
        migrations.AddField(
            model_name='individual',
            name='species_comment',
            field=models.CharField(blank=True, max_length=1024, verbose_name='comment (determination)'),
        ),
    ]
