# Generated by Django 5.2 on 2026-09-17 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('individuals', '0009_individual_projects'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='individual',
            unique_together=set(),
        ),
    ]
