# Generated by Django 5.2 on 2026-09-23 09:14

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('individuals', '0010_alter_individual_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='individual',
            options={'permissions': (('can_see_found_coordinates', 'Can see collecting coordinates'),), 'verbose_name': 'individual', 'verbose_name_plural': 'individuals'},
        ),
        migrations.AddField(
            model_name='individual',
            name='found_coordinates',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='collecting coordinates'),
        ),
    ]
