# Generated by Django 3.2 on 2021-04-19 11:30

import config_tables.admin
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(max_length=50, verbose_name='family')),
                ('subfamily', models.CharField(blank=True, max_length=50, verbose_name='subfamily')),
                ('tribus', models.CharField(blank=True, max_length=50, verbose_name='tribus')),
                ('subtribus', models.CharField(blank=True, max_length=50, verbose_name='subtribus')),
                ('genus', models.CharField(max_length=50, verbose_name='genus')),
                ('genus_author', models.CharField(blank=True, max_length=100, verbose_name='author')),
                ('full_name_generated', models.CharField(blank=True, max_length=350, verbose_name='full name')),
            ],
            options={
                'verbose_name': 'genus',
                'verbose_name_plural': 'genera',
                'ordering': ('genus', 'family'),
                'unique_together': {('family', 'subfamily', 'tribus', 'subtribus', 'genus', 'genus_author')},
            },
            bases=(models.Model, config_tables.admin.Configurable),
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=100, verbose_name='species')),
                ('species_author', models.CharField(blank=True, max_length=100, verbose_name='author species')),
                ('subspecies', models.CharField(blank=True, max_length=100, verbose_name='subspecies')),
                ('subspecies_author', models.CharField(blank=True, max_length=100, verbose_name='author subspec.')),
                ('variety', models.CharField(blank=True, max_length=200, verbose_name='variety')),
                ('variety_author', models.CharField(blank=True, max_length=100, verbose_name='author variety')),
                ('form', models.CharField(blank=True, max_length=200, verbose_name='form')),
                ('form_author', models.CharField(blank=True, max_length=100, verbose_name='author form')),
                ('cultivar', models.CharField(blank=True, help_text='without quotation marks', max_length=200, verbose_name='cultivar / breed')),
                ('full_name_generated', models.CharField(blank=True, max_length=200, verbose_name='full name')),
                ('deutscher_name', models.CharField(blank=True, max_length=200, verbose_name='german name')),
                ('synonyme', models.TextField(blank=True, null=True, verbose_name='synonyms')),
                ('area_of_distribution_etikettxt', models.CharField(blank=True, help_text='%', max_length=200, verbose_name='label text')),
                ('area_of_distribution_background', models.TextField(blank=True, verbose_name='detailed')),
                ('protection_of_species', models.CharField(blank=True, choices=[('LC', 'LC (Least Concern)'), ('NT', 'NT (Near Threatened)'), ('VU', 'VU (Vulnerable)'), ('EN', 'EN (Endangered)'), ('CR', 'CR (Critically Endangered)'), ('EW', 'EW (Extinct in the wild)'), ('EX', 'EX (Extinct)')], max_length=2, verbose_name='endangering')),
                ('poisonous_plant', models.BooleanField(blank=True, null=True, verbose_name='poisonous plant')),
                ('lifeform', models.CharField(blank=True, choices=[('P', 'Phanerophyt (Gehölz)'), ('C', 'Chamaephyt (Zwergstrauch/Halbstrauch)'), ('H', 'Hemikryptophyt (Staude)'), ('K', 'Kryptophyt'), ('T', 'Therophyt (Einjährige)')], max_length=2, verbose_name='life-form')),
                ('nomenclature_checked', models.BooleanField(blank=True, default=False, null=True, verbose_name='nomenclature checked')),
                ('comment', models.TextField(blank=True, max_length=10000, null=True, verbose_name='comment')),
                ('picture', models.ImageField(blank=True, upload_to='pictures', verbose_name='picture')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species.family', verbose_name='genus & family')),
            ],
            options={
                'verbose_name': 'species',
                'verbose_name_plural': 'species',
                'ordering': ('family__genus', 'species', 'subspecies'),
                'permissions': (('can_check_nomenclature', 'can check nomenclature of a species'),),
                'unique_together': {('family', 'species', 'species_author', 'subspecies', 'variety', 'form', 'cultivar')},
            },
            bases=(models.Model, config_tables.admin.Configurable),
        ),
    ]
