# Generated by Django 3.2 on 2023-03-01 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='species',
            unique_together={('family', 'species', 'species_author', 'subspecies', 'variety', 'form', 'cultivar', 'deutscher_name')},
        ),
    ]
