# Generated by Django 3.2 on 2025-03-09 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0002_alter_species_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='area_of_distribution_background',
        ),
        migrations.RemoveField(
            model_name='species',
            name='area_of_distribution_etikettxt',
        ),
    ]
