# Generated by Django 5.2 on 2026-01-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0002_alter_species_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='bnatschg_category',
            field=models.CharField(blank=True, choices=[('besonders', 'besonders geschützt'), ('streng', 'streng geschützt')], default='', help_text='Protection category according to Federal Nature Conservation Act', max_length=32, verbose_name='BNatSchG'),
        ),
        migrations.AlterField(
            model_name='species',
            name='lifeform',
            field=models.CharField(blank=True, choices=[('P', 'Phanerophyt (Gehölz)'), ('Pb', 'Phanerophyt (Baum)'), ('Ps', 'Phanerophyt (Strauch)'), ('C', 'Chamaephyt (Zwergstrauch/Halbstrauch)'), ('H', 'Hemikryptophyt (Staude)'), ('K', 'Kryptophyt'), ('T', 'Therophyt (Einjährige)'), ('A', 'Hydrophyt'), ('Ck', 'krautiger Chamaephyt'), ('G', 'Geophyt'), ('N', 'Nanophanerophyt'), ('Z', 'holziger Chamaephyt'), ('li', 'Liane / Spreizklimmer'), ('ep', 'Epiphyt'), ('hp', 'Halbparasit'), ('vp', 'Vollparasit'), ('1', 'einjährig'), ('2', 'zweijährig')], max_length=2, verbose_name='life-form'),
        ),
    ]
