# Generated by Django 3.2 on 2025-03-10 22:33

import config_tables.admin
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0003_auto_20250309_2237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ('category', 'species', 'subspecies'), 'permissions': (('can_check_nomenclature', 'can check nomenclature of a species'),), 'verbose_name': 'species', 'verbose_name_plural': 'species'},
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, null=True, verbose_name='category')),
                ('full_name_generated', models.CharField(blank=True, max_length=350, verbose_name='full name')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('category',),
                'unique_together': {('category',)},
            },
            bases=(models.Model, config_tables.admin.Configurable),
        ),
        migrations.AddField(
            model_name='species',
            name='category',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='species.category', verbose_name='category'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='species',
            unique_together={('category', 'species', 'species_author', 'subspecies', 'variety', 'form', 'cultivar', 'deutscher_name')},
        ),
        migrations.RemoveField(
            model_name='species',
            name='family',
        ),
        migrations.DeleteModel(
            name='Family',
        ),
    ]
