# Generated by Django 5.2 on 2026-07-20 11:12

import config_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0004_customprops'),
        ('species', '0003_species_bnatschg_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='custom_values_bool',
            field=config_app.fields.CustomPropertyValuesBoolField(related_name='family_values_bool', to='config_app.propertyvaluebool', verbose_name='bool values'),
        ),
        migrations.AddField(
            model_name='family',
            name='custom_values_text',
            field=config_app.fields.CustomPropertyValuesTextField(related_name='family_values_text', to='config_app.propertyvaluetext', verbose_name='text values'),
        ),
        migrations.AddField(
            model_name='family',
            name='custom_values_user',
            field=config_app.fields.CustomPropertyValuesUserField(related_name='family_values_user', to='config_app.propertyvalueuser', verbose_name='user values'),
        ),
        migrations.AddField(
            model_name='species',
            name='custom_values_bool',
            field=config_app.fields.CustomPropertyValuesBoolField(related_name='species_values_bool', to='config_app.propertyvaluebool', verbose_name='bool values'),
        ),
        migrations.AddField(
            model_name='species',
            name='custom_values_text',
            field=config_app.fields.CustomPropertyValuesTextField(related_name='species_values_text', to='config_app.propertyvaluetext', verbose_name='text values'),
        ),
        migrations.AddField(
            model_name='species',
            name='custom_values_user',
            field=config_app.fields.CustomPropertyValuesUserField(related_name='species_values_user', to='config_app.propertyvalueuser', verbose_name='user values'),
        ),
    ]
