# Generated by Django 3.2 on 2025-03-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0004_auto_20250310_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(default='category_default', max_length=50, verbose_name='category'),
            preserve_default=False,
        ),
    ]
