# Generated by Django 3.2 on 2025-03-14 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0005_alter_category_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
    ]
