# Generated by Django 3.2 on 2025-03-14 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0006_alter_category_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='species',
            options={'permissions': (('can_check_nomenclature', 'can check nomenclature of a species'),), 'verbose_name': 'species', 'verbose_name_plural': 'species'},
        ),
        migrations.AlterUniqueTogether(
            name='species',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='species',
            name='category',
        ),
    ]
