# Generated by Django 5.2 on 2026-09-10 11:12

import config_app.fields
import config_tables.admin
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config_app', '0004_customprops'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(blank=True, null=True, verbose_name='created at')),
                ('modified_date', models.DateField(blank=True, null=True, verbose_name='modified at')),
                ('abbreviation', models.CharField(blank=True, max_length=32, verbose_name='abbreviation')),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='start date')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('manager', models.TextField(blank=True, verbose_name='manager(s)')),
                ('partner', models.TextField(blank=True, verbose_name='partner(s)')),
                ('funding', models.TextField(blank=True, verbose_name='funding agency')),
                ('comment', models.TextField(blank=True, verbose_name='comment')),
                ('full_name_generated', models.CharField(editable=False, max_length=256, unique=True, verbose_name='full name')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_created_users', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('custom_values_bool', config_app.fields.CustomPropertyValuesBoolField(related_name='project_values_bool', to='config_app.propertyvaluebool', verbose_name='bool values')),
                ('custom_values_text', config_app.fields.CustomPropertyValuesTextField(related_name='project_values_text', to='config_app.propertyvaluetext', verbose_name='text values')),
                ('custom_values_user', config_app.fields.CustomPropertyValuesUserField(related_name='project_values_user', to='config_app.propertyvalueuser', verbose_name='user values')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_modified_users', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'ordering': ('full_name_generated',),
            },
            bases=(config_tables.admin.Configurable, models.Model),
        ),
    ]
