# Generated by Django 5.2 on 2026-09-08 12:06

import config_app.fields
import config_tables.admin
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config_app', '0004_customprops'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Literature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(blank=True, null=True, verbose_name='created at')),
                ('modified_date', models.DateField(blank=True, null=True, verbose_name='modified at')),
                ('authors', models.CharField(blank=True, max_length=128, verbose_name='author(s)')),
                ('title', models.CharField(blank=True, max_length=128, verbose_name='title')),
                ('compilation', models.CharField(blank=True, max_length=128, verbose_name='compilation/magazine')),
                ('volume', models.CharField(blank=True, max_length=64, verbose_name='volume')),
                ('print_run', models.CharField(blank=True, max_length=32, verbose_name='print run')),
                ('year', models.SmallIntegerField(blank=True, null=True, verbose_name='year')),
                ('page', models.CharField(blank=True, max_length=32, verbose_name='page(s)')),
                ('place', models.CharField(blank=True, max_length=64, verbose_name='place')),
                ('publisher', models.CharField(blank=True, max_length=128, verbose_name='publisher')),
                ('keywords', models.CharField(blank=True, max_length=256, verbose_name='keywords')),
                ('location', models.CharField(blank=True, help_text='Where to find it', max_length=128, verbose_name='location')),
                ('signature', models.CharField(blank=True, max_length=64, verbose_name='signature')),
                ('full_name_generated', models.CharField(editable=False, max_length=4096, unique=True, verbose_name='full name')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='literature_created_users', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('custom_values_bool', config_app.fields.CustomPropertyValuesBoolField(related_name='literature_values_bool', to='config_app.propertyvaluebool', verbose_name='bool values')),
                ('custom_values_text', config_app.fields.CustomPropertyValuesTextField(related_name='literature_values_text', to='config_app.propertyvaluetext', verbose_name='text values')),
                ('custom_values_user', config_app.fields.CustomPropertyValuesUserField(related_name='literature_values_user', to='config_app.propertyvalueuser', verbose_name='user values')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='literature_modified_users', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
            ],
            options={
                'verbose_name': 'literature',
                'verbose_name_plural': 'literatures',
                'ordering': ('title', 'year'),
                'unique_together': {('title', 'compilation', 'volume', 'print_run', 'year', 'page', 'location')},
            },
            bases=(config_tables.admin.Configurable, models.Model),
        ),
    ]
