# Generated by Django 5.2 on 2025-10-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrybook', '0002_accession_number_as_char'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='external_order_number',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='External order number'),
        ),
    ]
