# Generated by Django 5.2 on 2026-07-21 11:41

import config_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0004_customprops'),
        ('entrybook', '0002_add_and_alter_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='custom_values_bool',
            field=config_app.fields.CustomPropertyValuesBoolField(related_name='entry_values_bool', to='config_app.propertyvaluebool', verbose_name='bool values'),
        ),
        migrations.AddField(
            model_name='entry',
            name='custom_values_text',
            field=config_app.fields.CustomPropertyValuesTextField(related_name='entry_values_text', to='config_app.propertyvaluetext', verbose_name='text values'),
        ),
    ]
