# Generated by Django 5.2 on 2026-07-21 11:41

from django.db import migrations, models
from django.conf import settings
import config_app.fields
import tools.global_request


def clear_creation_fields(apps, schema_editor):
    for Model in (
            apps.get_model('entrybook', 'Entry'),
    ):
        Model.objects.all().update(created_date=None, modified_date=None)


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0004_customprops'),
        ('entrybook', '0002_add_and_alter_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='custom_values_bool',
            field=config_app.fields.CustomPropertyValuesBoolField(related_name='entry_values_bool', to='config_app.propertyvaluebool', verbose_name='bool values'),
        ),
        migrations.AddField(
            model_name='entry',
            name='custom_values_text',
            field=config_app.fields.CustomPropertyValuesTextField(related_name='entry_values_text', to='config_app.propertyvaluetext', verbose_name='text values'),
        ),
        migrations.AddField(
            model_name='entry',
            name='custom_values_user',
            field=config_app.fields.CustomPropertyValuesUserField(related_name='entry_values_user', to='config_app.propertyvalueuser', verbose_name='user values'),
        ),
        migrations.AddField(
            model_name='entry',
            name='created_by',
            field=models.ForeignKey(null=True, blank=True, on_delete=models.deletion.CASCADE, related_name='entry_created_users', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='entry',
            name='created_date',
            field=models.DateField(null=True, blank=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='entry',
            name='modified_by',
            field=models.ForeignKey(null=True, blank=True, on_delete=models.deletion.CASCADE, related_name='entry_modified_users', to=settings.AUTH_USER_MODEL, verbose_name='modified by'),
        ),
        migrations.AddField(
            model_name='entry',
            name='modified_date',
            field=models.DateField(null=True, blank=True, verbose_name='modified at'),
        ),

        migrations.RunPython(clear_creation_fields, migrations.RunPython.noop),
    ]
