# Generated by Django 5.2 on 2026-09-08 13:58

import django.db.models.deletion
import individuals.numbers
from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('entrybook', '0003_customprops'),
        ('literature', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='literature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='literature.literature', verbose_name='literature'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='accession_number',
            field=models.CharField(db_collation='natural_sort' if settings.IS_POSTGRES else None, db_index=True, default=individuals.numbers.get_new_accession_number, max_length=30, null=True, unique=True, verbose_name='accession #'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='collector_number',
            field=models.CharField(blank=True, db_collation='natural_sort' if settings.IS_POSTGRES else None, max_length=100, verbose_name='collection number'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='id_name_generated',
            field=models.CharField(db_collation='natural_sort' if settings.IS_POSTGRES else None, default='', editable=False, max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='order_number',
            field=models.CharField(db_collation='natural_sort' if settings.IS_POSTGRES else None, default=individuals.numbers.get_new_order_number, max_length=20, unique=True, verbose_name='order number'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='sowing_number',
            field=models.CharField(blank=True, db_collation='natural_sort' if settings.IS_POSTGRES else None, max_length=100, verbose_name='sowing number'),
        ),
    ]
