# Generated by Django 5.2 on 2026-09-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrybook', '0004_entry_literature'),
        ('meta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='entries', to='meta.project', verbose_name='project assignment'),
        ),
        migrations.AddField(
            model_name='entry',
            name='species_comment',
            field=models.CharField(blank=True, max_length=1024, verbose_name='comment (determination)'),
        ),
    ]
