# Generated by Django 5.2 on 2026-09-17 09:01

import config_app.fields
import config_tables.admin
import django.db.models.deletion
import individuals.numbers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botman', '0008_natural_sort_collation'),
        ('config_app', '0004_customprops'),
        ('entrybook', '0005_entry_projects'),
        ('individuals', '0009_individual_projects'),
        ('meta', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(blank=True, null=True, verbose_name='created at')),
                ('modified_date', models.DateField(blank=True, null=True, verbose_name='modified at')),
                ('dispatch_number', models.CharField(db_collation='natural_sort', db_index=True, default=individuals.numbers.get_new_dispatch_number, max_length=32, unique=True, verbose_name='dispatch number')),
                ('date', models.DateField(auto_now_add=True, db_index=True, verbose_name='event date')),
                ('transfer_type', models.CharField(choices=[('plant', 'Plant'), ('leave', 'Leave'), ('branch', 'Branch'), ('seed', 'Seed'), ('scion', 'Scion'), ('gene_sample', 'Gene sample'), ('biomass', 'Biomass')], db_index=True, max_length=32, verbose_name='transfer type')),
                ('amount', models.CharField(db_collation='natural_sort', db_index=True, max_length=32, verbose_name='amount')),
                ('comment', models.TextField(blank=True, max_length=2048, verbose_name='comment')),
                ('id_name_generated', models.CharField(db_index=True, editable=False, max_length=256, unique=True, verbose_name='name')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_created_users', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('custom_values_bool', config_app.fields.CustomPropertyValuesBoolField(related_name='dispatch_values_bool', to='config_app.propertyvaluebool', verbose_name='bool values')),
                ('custom_values_text', config_app.fields.CustomPropertyValuesTextField(related_name='dispatch_values_text', to='config_app.propertyvaluetext', verbose_name='text values')),
                ('custom_values_user', config_app.fields.CustomPropertyValuesUserField(related_name='dispatch_values_user', to='config_app.propertyvalueuser', verbose_name='user values')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='botman.botanicgarden', verbose_name='destination')),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='individuals.individual', verbose_name='individual')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_modified_users', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
                ('projects', models.ManyToManyField(blank=True, db_index=True, related_name='dispatches', to='meta.project', verbose_name='project assignment')),
                ('transfer_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to=settings.AUTH_USER_MODEL, verbose_name='transfer by')),
            ],
            options={
                'verbose_name': 'dispatch',
                'verbose_name_plural': 'dispatches',
                'ordering': ('date', 'dispatch_number'),
            },
            bases=(config_tables.admin.Configurable, models.Model),
        ),
    ]
