# Generated by Django 5.2 on 2026-09-23 10:24

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrybook', '0006_dispatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='found_coordinates',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='collecting coordinates'),
        ),
    ]
