# Generated by Django 3.2 on 2021-04-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('individuals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeedCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateField(verbose_name='release date')),
                ('valid_until_date', models.DateField(blank=True, null=True, verbose_name='valid until')),
                ('is_finalized', models.BooleanField(default=False, editable=False, verbose_name='finalized')),
                ('copyright_note', models.TextField(blank=True, help_text='LaTeX syntax allowed', max_length=10000, verbose_name='copyright note')),
                ('preface', models.TextField(blank=True, help_text='LaTeX syntax allowed', max_length=10000, verbose_name='preface')),
                ('notes', models.TextField(blank=True, help_text='LaTeX syntax allowed', max_length=10000, verbose_name='notes')),
                ('debug_output', models.TextField(blank=True, default='', editable=False, verbose_name='debug output')),
                ('seed', models.ManyToManyField(blank=True, to='individuals.Individual', verbose_name='seed')),
            ],
            options={
                'verbose_name': 'seed catalog',
                'verbose_name_plural': 'seed catalogs',
                'permissions': (('can_finalize_catalog', 'can finalize a seed catalog'),),
            },
        ),
    ]
