# Generated by Django 3.2 on 2025-03-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seedcatalog', '0002_add_catalog_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seedcatalog',
            name='title_sub',
            field=models.TextField(blank=True, null=True, verbose_name='Sub-title of catalog'),
        ),
    ]
