# Generated by Django 3.2 on 2021-04-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('t', 'translateable text'), ('j', 'json')], default='t', max_length=1, verbose_name='type')),
                ('key', models.CharField(max_length=255, unique=True, verbose_name='key')),
                ('value', models.TextField(blank=True, default='', verbose_name='value')),
                ('value_de', models.TextField(blank=True, default='', null=True, verbose_name='value')),
                ('value_en', models.TextField(blank=True, default='', null=True, verbose_name='value')),
                ('value_json', models.JSONField(blank=True, null=True, verbose_name='json value')),
            ],
            options={
                'verbose_name': 'Variable',
                'verbose_name_plural': 'Variables',
            },
        ),
    ]
