# Generated by Django 5.2 on 2026-05-29 09:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyvalue',
            name='value_geo',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='geo location'),
        ),
        migrations.AlterField(
            model_name='keyvalue',
            name='type',
            field=models.CharField(choices=[('t', 'translateable text'), ('j', 'json'), ('g', 'geo coordinate')], default='t', max_length=1, verbose_name='type'),
        ),
    ]
