# Generated by Django 5.2 on 2026-07-01 18:02

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyvalue',
            name='value_normal_text',
            field=models.TextField(blank=True, default='', verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='keyvalue',
            name='type',
            field=models.CharField(choices=[('t', 'translateable text'), ('n', 'normal text'), ('j', 'json'), ('g', 'geo coordinate')], default='t', max_length=1, verbose_name='type'),
        ),
    ]
