# Generated by Django 5.2 on 2026-07-07 00:10

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0002_add_value_normal_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyvalue',
            name='value_geo',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='geo location'),
        ),
    ]
