# Generated by Django 5.2 on 2026-07-19 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0003_keyvalue_value_geo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('model', models.CharField(choices=[('species.Species', 'species')], max_length=64, verbose_name='model')),
                ('type', models.CharField(choices=[('bool', 'Boolean'), ('text', 'Text')], verbose_name='type')),
                ('name', models.CharField(unique=True, verbose_name='name')),
                ('order', models.IntegerField(default=0, help_text='Order of value when viewing or editing.', verbose_name='order')),
            ],
            options={
                'verbose_name': 'custom property',
                'verbose_name_plural': 'custom properties',
                'ordering': ('model', 'name'),
                'unique_together': {('model', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PropertyValueBool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField(verbose_name='value')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values_bool', to='config_app.customproperty', verbose_name='custom property')),
            ],
            options={
                'verbose_name': 'boolean value',
                'verbose_name_plural': 'boolean values',
            },
        ),
        migrations.CreateModel(
            name='PropertyValueText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=256, verbose_name='value')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values_text', to='config_app.customproperty', verbose_name='custom property')),
            ],
            options={
                'verbose_name': 'text value',
                'verbose_name_plural': 'text values',
            },
        ),
    ]
