# Generated by Django 5.2 on 2026-07-20 11:12

import django.db.models.deletion
from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0003_keyvalue_value_geo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('model', models.CharField(
                    # these are copied from `config_app/models/customprops.py`
                    # When adding a new model, the choices just should be added here
                    # instead of creating a new migration file with that sole purpose.
                    # (unless there is a new config_app migration file already)
                    choices=(
                        ("botman.BGCIGarden", ("BGCI garden")),
                        ("botman.BotanicGarden", ("botanic garden")),
                        ("individuals.Territory", ("territory")),
                        ("individuals.Department", ("department")),
                        ("species.Family", ("genus")),
                        ("species.Species", ("species")),
                        ("entrybook.Entry", ("Seed/individual entry")),
                        ("individuals.Individual", ("individual")),
                        ("herbaria.Herbarium", ("Herbarium")),
                        ("herbaria.HerbariumSpecimen", ("Specimen")),
                    ),
                    max_length=64, verbose_name='model')
                 ),
                ('type', models.CharField(choices=[('bool', 'Boolean'), ('text', 'Text'), ('text_long', 'Text (long)'), ('user', 'User')], verbose_name='type')),
                ('name', models.CharField(verbose_name='name')),
                ('required', models.BooleanField(verbose_name='mandatory', default=False)),
                ('order', models.IntegerField(default=0, help_text='Order of field when viewing or editing.', verbose_name='order')),
                ('choices', models.TextField(blank=True, help_text='For text properties, limits the selection to these items, one per line', verbose_name='choices')),
            ],
            options={
                'verbose_name': 'custom property',
                'verbose_name_plural': 'custom properties',
                'ordering': ('model', 'name'),
                'unique_together': {('model', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PropertyValueBool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField(verbose_name='value')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values_bool', to='config_app.customproperty', verbose_name='custom property')),
            ],
            options={
                'verbose_name': 'boolean value',
                'verbose_name_plural': 'boolean values',
            },
        ),
        migrations.CreateModel(
            name='PropertyValueText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=256, verbose_name='value')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values_text', to='config_app.customproperty', verbose_name='custom property')),
            ],
            options={
                'verbose_name': 'text value',
                'verbose_name_plural': 'text values',
            },
        ),
        migrations.CreateModel(
            name='PropertyValueUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values_user', to='config_app.customproperty', verbose_name='custom property')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='value')),
            ],
            options={
                'verbose_name': 'user value',
                'verbose_name_plural': 'user values',
            },
        ),
    ]
