# Generated by Django 5.2 on 2026-07-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0004_customprops'),
    ]

    operations = [
        migrations.AddField(
            model_name='customproperty',
            name='choices',
            field=models.TextField(blank=True, help_text='For text properties, limits the selection to these items, one per line', verbose_name='choices'),
        ),
    ]
