# Generated by Django 5.2 on 2026-07-19 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0005_customproperty_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customproperty',
            name='model',
            field=models.CharField(choices=[('species.Family', 'family'), ('species.Species', 'species'), ('botman.BotanicGarden', 'botanic garden')], max_length=64, verbose_name='model'),
        ),
        migrations.AlterField(
            model_name='customproperty',
            name='type',
            field=models.CharField(choices=[('bool', 'Boolean'), ('text', 'Text'), ('text_long', 'Text (long)')], verbose_name='type'),
        ),
    ]
