ISO_COUNTRY_CHOICES = (
    ('xx', 'xx UNKNOWN'),
    ('ad', 'AD (Andorra, Principality of)'),
    ('ae', 'AE (United Arab Emirates)'),
    ('af', 'AF (Afghanistan, Islamic State of)'),
    ('ag', 'AG (Antigua and Barbuda)'),
    ('ai', 'AI (Anguilla)'),
    ('al', 'AL (Albania)'),
    ('am', 'AM (Armenia)'),
    ('an', 'AN (Netherlands Antilles)'),
    ('ao', 'AO (Angola)'),
    ('aq', 'AQ (Antarctica)'),
    ('ar', 'AR (Argentina)'),
    ('as', 'AS (American Samoa)'),
    ('at', 'AT (Austria)'),
    ('au', 'AU (Australia)'),
    ('aw', 'AW (Aruba)'),
    ('az', 'AZ (Azerbaidjan)'),
    ('ba', 'BA (Bosnia-Herzegovina)'),
    ('bb', 'BB (Barbados)'),
    ('bd', 'BD (Bangladesh)'),
    ('be', 'BE (Belgium)'),
    ('bf', 'BF (Burkina Faso)'),
    ('bg', 'BG (Bulgaria)'),
    ('bh', 'BH (Bahrain)'),
    ('bi', 'BI (Burundi)'),
    ('bj', 'BJ (Benin)'),
    ('bm', 'BM (Bermuda)'),
    ('bn', 'BN (Brunei Darussalam)'),
    ('bo', 'BO (Bolivia)'),
    ('br', 'BR (Brazil)'),
    ('bs', 'BS (Bahamas)'),
    ('bt', 'BT (Bhutan)'),
    ('bv', 'BV (Bouvet Island)'),
    ('bw', 'BW (Botswana)'),
    ('by', 'BY (Belarus)'),
    ('bz', 'BZ (Belize)'),
    ('ca', 'CA (Canada)'),
    ('cc', 'CC (Cocos Islands)'),
    ('cf', 'CF (Central African Republic)'),
    ('cd', 'CD (Congo, The Democratic Republic of the)'),
    ('cg', 'CG (Congo)'),
    ('ch', 'CH (Switzerland)'),
    ('ci', "CI (Ivory Coast/Cote D'Ivoire)"),
    ('ck', 'CK (Cook Islands)'),
    ('cl', 'CL (Chile)'),
    ('cm', 'CM (Cameroon)'),
    ('cn', 'CN (China)'),
    ('co', 'CO (Colombia)'),
    ('cr', 'CR (Costa Rica)'),
    ('cs', 'CS (former Czechoslovakia)'),
    ('cu', 'CU (Cuba)'),
    ('cv', 'CV (Cape Verde)'),
    ('cx', 'CX (Christmas Island)'),
    ('cy', 'CY (Cyprus)'),
    ('cz', 'CZ (Czech Republic)'),
    ('de', 'DE (Germany)'),
    ('dj', 'DJ (Djibouti)'),
    ('dk', 'DK (Denmark)'),
    ('dm', 'DM (Dominica)'),
    ('do', 'DO (Dominican Republic)'),
    ('dz', 'DZ (Algeria)'),
    ('ec', 'EC (Ecuador)'),
    ('ee', 'EE (Estonia)'),
    ('eg', 'EG (Egypt)'),
    ('eh', 'EH (Western Sahara)'),
    ('er', 'ER (Eritrea)'),
    ('es', 'ES (Spain)'),
    ('et', 'ET (Ethiopia)'),
    ('fi', 'FI (Finland)'),
    ('fj', 'FJ (Fiji)'),
    ('fk', 'FK (Falkland Islands)'),
    ('fm', 'FM (Micronesia)'),
    ('fo', 'FO (Faroe Islands)'),
    ('fr', 'FR (France)'),
    ('fx', 'FX (France, European Territory)'),
    ('ga', 'GA (Gabon)'),
    ('gb', 'GB (Great Britain)'),
    ('gd', 'GD (Grenada)'),
    ('ge', 'GE (Georgia)'),
    ('gf', 'GF (French Guyana)'),
    ('gh', 'GH (Ghana)'),
    ('gi', 'GI (Gibraltar)'),
    ('gl', 'GL (Greenland)'),
    ('gm', 'GM (Gambia)'),
    ('gn', 'GN (Guinea)'),
    ('gp', 'GP (French Guadeloupe)'),
    ('gq', 'GP (Equatorial Guinea)'),
    ('gr', 'GR (Greece)'),
    ('gs', 'GS (S. Georgia & S. Sandwich Isls.)'),
    ('gt', 'GT (Guatemala)'),
    ('gu', 'GU (Guam (USA))'),
    ('gw', 'GW (Guinea Bissau)'),
    ('gy', 'GY (Guyana)'),
    ('hk', 'HK (Hong Kong)'),
    ('hm', 'HM (Heard and McDonald Islands)'),
    ('hn', 'HN (Honduras)'),
    ('hr', 'HR (Croatia)'),
    ('ht', 'HT (Haiti)'),
    ('hu', 'HU (Hungary)'),
    ('id', 'ID (Indonesia)'),
    ('ie', 'IE (Ireland)'),
    ('il', 'IL (Israel)'),
    ('in', 'IN (India)'),
    #('in', 'IN (International)'),
    ('io', 'IO (British Indian Ocean Territory)'),
    ('iq', 'IQ (Iraq)'),
    ('ir', 'IR (Iran)'),
    ('is', 'IS (Iceland)'),
    ('it', 'IT (Italy)'),
    ('jm', 'JM (Jamaica)'),
    ('jo', 'JO (Jordan)'),
    ('jp', 'JP (Japan)'),
    ('ke', 'KE (Kenya)'),
    ('kg', 'KG (Kyrgyz Republic, Kyrgyzstan)'),
    ('kh', 'KH (Cambodia, Kingdom of)'),
    ('ki', 'KI (Kiribati)'),
    ('km', 'KM (Comoros)'),
    ('kn', 'KN (Saint Kitts & Nevis Anguilla)'),
    ('kp', 'KP (North Korea)'),
    ('kr', 'KR (South Korea)'),
    ('kw', 'KW (Kuwait)'),
    ('ky', 'KY (Cayman Islands)'),
    ('kz', 'KZ (Kazakhstan)'),
    ('la', 'LA (Laos)'),
    ('lb', 'LB (Lebanon)'),
    ('lc', 'LC (Saint Lucia)'),
    ('li', 'LI (Liechtenstein)'),
    ('lk', 'LK (Sri Lanka)'),
    ('lr', 'LR (Liberia)'),
    ('ls', 'LS (Lesotho)'),
    ('lt', 'LT (Lithuania)'),
    ('lu', 'LU (Luxembourg)'),
    ('lv', 'LV (Latvia)'),
    ('ly', 'LY (Libya)'),
    ('ma', 'MA (Morocco)'),
    ('mc', 'MC (Monaco)'),
    ('md', 'MD (Moldavia)'),
    ('me', 'ME (Montenegro)'),
    ('mg', 'MG (Madagascar)'),
    ('mh', 'MH (Marshall Islands)'),
    ('mi', 'MI (USA Military)'),
    ('mk', 'MK (Macedonia)'),
    ('ml', 'ML (Mali)'),
    ('mm', 'MM (Myanmar)'),
    ('mn', 'MN (Mongolia)'),
    ('mo', 'MO (Macau)'),
    ('mp', 'MP (Northern Mariana Islands)'),
    ('mq', 'MQ (Martinique (French))'),
    ('mr', 'MR (Mauritania)'),
    ('ms', 'MS (Montserrat)'),
    ('mt', 'MT (Malta)'),
    ('mu', 'MU (Mauritius)'),
    ('mv', 'MV (Maldives)'),
    ('mw', 'MW (Malawi)'),
    ('mx', 'MX (Mexico)'),
    ('my', 'MY (Malaysia)'),
    ('mz', 'MZ (Mozambique)'),
    ('na', 'NA (Namibia)'),
    ('nc', 'NC (New Caledonia (French))'),
    ('ne', 'NE (Niger)'),
    ('ne', 'NE (Network)'),
    ('nf', 'NF (Norfolk Island)'),
    ('ng', 'NG (Nigeria)'),
    ('ni', 'NI (Nicaragua)'),
    ('nl', 'NL (Netherlands)'),
    ('no', 'NO (Norway)'),
    ('np', 'NP (Nepal)'),
    ('nr', 'NR (Nauru)'),
    ('nt', 'NT (Neutral Zone)'),
    ('nu', 'NU (Niue)'),
    ('nz', 'NZ (New Zealand)'),
    ('om', 'OM (Oman)'),
    ('or', 'OR (Non-Profit Making Organisations (sic))'),
    ('pa', 'PA (Panama)'),
    ('pe', 'PE (Peru)'),
    ('pf', 'PF (Polynesia (French))'),
    ('pg', 'PG (Papua New Guinea)'),
    ('ph', 'PH (Philippines)'),
    ('pk', 'PK (Pakistan)'),
    ('pl', 'PL (Poland)'),
    ('pm', 'PM (Saint Pierre and Miquelon)'),
    ('pn', 'PN (Pitcairn Island)'),
    ('pr', 'PR (Puerto Rico)'),
    ('pt', 'PT (Portugal)'),
    ('pw', 'PW (Palau)'),
    ('py', 'PY (Paraguay)'),
    ('qa', 'QA (Qatar)'),
    ('re', 'RE (Reunion (French))'),
    ('ro', 'RO (Romania)'),
    ('rs', 'RS (Serbia)'),
    ('ru', 'RU (Russian Federation)'),
    ('rw', 'RW (Rwanda)'),
    ('sa', 'SA (Saudi Arabia)'),
    ('sb', 'SB (Solomon Islands)'),
    ('sc', 'SC (Seychelles)'),
    ('sd', 'SD (Sudan)'),
    ('se', 'SE (Sweden)'),
    ('sg', 'SG (Singapore)'),
    ('sh', 'SH (Saint Helena)'),
    ('si', 'SI (Slovenia)'),
    ('sj', 'SJ (Svalbard and Jan Mayen Islands)'),
    ('sk', 'SK (Slovak Republic)'),
    ('sl', 'SL (Sierra Leone)'),
    ('sm', 'SM (San Marino)'),
    ('sn', 'SN (Senegal)'),
    ('so', 'SO (Somalia)'),
    ('sr', 'SR (Suriname)'),
    ('st', 'ST (Saint Tome (Sao Tome) and Principe)'),
    ('su', 'SU (USSR (former))'),
    ('sv', 'SV (El Salvador)'),
    ('sy', 'SY (Syria)'),
    ('sz', 'SZ (Swaziland)'),
    ('tc', 'TC (Turks and Caicos Islands)'),
    ('td', 'TD (Chad)'),
    ('tf', 'TF (French Southern Territories)'),
    ('tg', 'TG (Togo)'),
    ('th', 'TH (Thailand)'),
    ('tj', 'TJ (Tadjikistan)'),
    ('tk', 'TK (Tokelau)'),
    ('tm', 'TM (Turkmenistan)'),
    ('tn', 'TN (Tunisia)'),
    ('to', 'TO (Tonga)'),
    ('tp', 'TP (East Timor)'),
    ('tr', 'TR (Turkey)'),
    ('tt', 'TT (Trinidad and Tobago)'),
    ('tv', 'TV (Tuvalu)'),
    ('tw', 'TW (Taiwan)'),
    ('tz', 'TZ (Tanzania)'),
    ('ua', 'UA (Ukraine)'),
    ('ug', 'UG (Uganda)'),
    ('uk', 'UK (United Kingdom)'),
    ('um', 'UM (USA Minor Outlying Islands)'),
    ('us', 'US (United States)'),
    ('uy', 'UY (Uruguay)'),
    ('uz', 'UZ (Uzbekistan)'),
    ('va', 'VA (Holy See (Vatican City State))'),
    ('vc', 'VC (Saint Vincent & Grenadines)'),
    ('ve', 'VE (Venezuela)'),
    ('vg', 'VG (Virgin Islands (British))'),
    ('vi', 'VI (Virgin Islands (USA))'),
    ('vn', 'VN (Vietnam)'),
    ('vu', 'VU (Vanuatu)'),
    ('wf', 'WF (Wallis and Futuna Islands)'),
    ('ws', 'WS (Samoa)'),
    ('ye', 'YE (Yemen)'),
    ('yt', 'YT (Mayotte)'),
    ('yu', 'YU (Yugoslavia)'),
    ('za', 'ZA (South Africa)'),
    ('zm', 'ZM (Zambia)'),
    ('zr', 'ZR (Zaire)'),
    ('zw', 'ZW (Zimbabwe)'),
)


def get_iso_country_by_id(id):
    for i in ISO_COUNTRY_CHOICES:
        if i[0].lower() == id.lower():
            return i[1]
    return ISO_COUNTRY_CHOICES[0][1]
