# Generated by Django 3.2 on 2021-04-19 11:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabelDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_name', models.CharField(help_text="This name is used to identify a label type in a label ticket. You can replace a label by reusing it's identification name", max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[0-9A-Za-z_]+$', 'Only alphanumeric characters and _ are allowed.')], verbose_name='identification')),
                ('display_name', models.CharField(max_length=50, verbose_name='display name')),
                ('type', models.CharField(choices=[('garden', 'Botanic Garden'), ('individual', 'Individual')], default='individual', max_length=30, verbose_name='label type')),
                ('svg_markup', models.TextField(verbose_name='svg')),
            ],
            options={
                'verbose_name': 'Label',
                'verbose_name_plural': 'Labels',
            },
        ),
    ]
