# Generated by Django 3.2 on 2021-05-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labeldefinition',
            name='format',
            field=models.CharField(choices=[('svg', 'SVG (Vector Graphics)'), ('csv', 'CSV (Table)')], default='svg', max_length=16, verbose_name='label format'),
        ),
        migrations.AlterField(
            model_name='labeldefinition',
            name='svg_markup',
            field=models.TextField(verbose_name='markup'),
        ),
    ]
