# Generated by Django 3.2 on 2024-05-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_add_csv_label_format'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labeldefinition',
            old_name='svg_markup',
            new_name='markup',
        ),
        migrations.AlterField(
            model_name='labeldefinition',
            name='type',
            field=models.CharField(choices=[('garden', 'Botanic Garden'), ('individual', 'Individual'), ('entry', 'Entry')], default='individual', max_length=30, verbose_name='label type'),
        ),
    ]
