# Generated by Django 3.2 on 2024-05-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0003_rename_markup_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labeldefinition',
            name='format',
            field=models.CharField(choices=[('svg', 'SVG (Vector Graphics)'), ('csv', 'CSV (Table)'), ('html', 'HTML (Page)')], default='svg', max_length=16, verbose_name='label format'),
        ),
        migrations.AddField(
            model_name='labeldefinition',
            name='page_markup',
            field=models.TextField(blank=True, help_text='The outer template for HTML. The rendered markup from above is available as {{content}}', null=True, verbose_name='page markup'),
        ),
        migrations.AlterField(
            model_name='labeldefinition',
            name='markup',
            field=models.TextField(help_text='The template for SVG, CSV or HTML', verbose_name='markup'),
        ),
    ]
