# Generated by Django 3.2 on 2021-04-22 13:47

import botman.models
import config_tables.admin
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotanicGarden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='name')),
                ('code', models.CharField(blank=True, db_index=True, max_length=6, null=True, verbose_name='IPEN part')),
                ('number', models.IntegerField(default=botman.models.get_new_number, unique=True, verbose_name='garden number')),
                ('address', models.TextField(blank=True, max_length=255, null=True, verbose_name='address')),
                ('phone', models.CharField(blank=True, max_length=80, null=True, verbose_name='phone')),
                ('website', models.URLField(blank=True, null=True, verbose_name='website')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('full_name_generated', models.CharField(blank=True, max_length=150, verbose_name='full name')),
            ],
            options={
                'verbose_name': 'botanic garden',
                'verbose_name_plural': 'botanic gardens',
                'ordering': ('number',),
            },
            bases=(config_tables.admin.Configurable, models.Model),
        ),
    ]
