# Generated by Django 3.2 on 2021-09-29 09:28

import config_tables.admin
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('botman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botanicgarden',
            name='catalog_date_generated',
            field=models.DateField(null=True, verbose_name='latest catalog date'),
        ),
        migrations.AddField(
            model_name='botanicgarden',
            name='num_orders_generated',
            field=models.IntegerField(default=0, verbose_name='number of orders'),
        ),
        migrations.CreateModel(
            name='OutgoingOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now=True, verbose_name='Creation date')),
                ('order_text', models.TextField(verbose_name='Order text')),
                ('processed', models.BooleanField(default=False, verbose_name='Processed')),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_orders', to='botman.botanicgarden', verbose_name='Botanic garden')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_orders', to=settings.AUTH_USER_MODEL, verbose_name='Ordered by user')),
            ],
            options={
                'verbose_name': 'outgoing order',
                'verbose_name_plural': 'outgoing orders',
                'ordering': ('date_created',),
            },
            bases=(config_tables.admin.Configurable, models.Model),
        ),
        migrations.CreateModel(
            name='ExternalCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_uploaded', models.DateField(default=django.utils.timezone.now, verbose_name='Date incoming')),
                ('date_outgoing', models.DateField(blank=True, null=True, verbose_name='Date outgoing')),
                ('file', models.FileField(upload_to='garden-catalogs/', verbose_name='Catalog file')),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogs', to='botman.botanicgarden', verbose_name='Botanic garden')),
            ],
            options={
                'verbose_name': 'external catalog',
                'verbose_name_plural': 'external catalogs',
                'ordering': ('date_uploaded',),
            },
            bases=(config_tables.admin.Configurable, models.Model),
        ),
    ]
