# Generated by Django 3.2 on 2023-05-24 13:02

import config_tables.admin
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('botman', '0002_external_catalogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalCatalogArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_uploaded', models.DateField(default=django.utils.timezone.now, verbose_name='Date incoming')),
                ('date_outgoing', models.DateField(blank=True, null=True, verbose_name='Date outgoing')),
                ('file', models.FileField(upload_to='garden-catalogs/', verbose_name='Catalog file')),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogs_archived', to='botman.botanicgarden', verbose_name='Botanic garden')),
            ],
            options={
                'verbose_name': 'external catalog (archived)',
                'verbose_name_plural': 'external catalogs (archived)',
                'ordering': ('date_uploaded',),
            },
            bases=(config_tables.admin.Configurable, models.Model),
        ),
    ]
