# Generated by Django 5.2 on 2025-10-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botman', '0004_bgcigarden'),
    ]

    operations = [
        migrations.AddField(
            model_name='botanicgarden',
            name='comment',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='comment'),
        ),
    ]
