# Generated by Django 5.2 on 2026-06-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botman', '0005_botanicgarden_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botanicgarden',
            name='name',
            field=models.CharField(db_index=True, max_length=120, unique=True, verbose_name='name'),
        ),
    ]
