# Generated by Django 5.2 on 2026-07-13 18:29

import botman.models.garden
from django.db import migrations, models
from django.contrib.postgres.operations import CreateCollation
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('botman', '0005_botanicgarden_comment'),
    ]

    operations = (
        [] if not settings.IS_POSTGRES
        else [
            # create collation for "natural sorting"
            # https://cscheng.info/2025/07/10/applying-natural-sort-to-a-django-charfield-with-postgresql.html
            CreateCollation(
                name="natural_sort",
                provider="icu",
                locale="de-u-kn-true",
            ),
        ]
    ) + [
        migrations.AlterField(
            model_name='botanicgarden',
            name='name',
            field=models.CharField(db_index=True, max_length=120, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='botanicgarden',
            name='number',
            field=models.CharField(default=botman.models.garden.get_new_number, max_length=16, unique=True, verbose_name='garden number', db_collation='natural_sort' if settings.IS_POSTGRES else None),
        ),
    ]
