# Generated by Django 5.2 on 2026-07-14 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botman', '0005_botanicgarden_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='botanicgarden',
            name='bgci_id',
            field=models.IntegerField(blank=True, help_text='ID of garden in https://gardensearch.bgci.org (0 if garden not in BGCI)', null=True, verbose_name='BGCI ID'),
        ),
        migrations.AlterField(
            model_name='botanicgarden',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
    ]
