# Generated by Django 5.2 on 2026-07-20 11:13

import config_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botman', '0006_botanicgarden_add_bgci_id_alter_comment'),
        ('config_app', '0004_customprops'),
    ]

    operations = [
        migrations.AddField(
            model_name='botanicgarden',
            name='custom_values_bool',
            field=config_app.fields.CustomPropertyValuesBoolField(related_name='garden_values_bool', to='config_app.propertyvaluebool', verbose_name='bool values'),
        ),
        migrations.AddField(
            model_name='botanicgarden',
            name='custom_values_text',
            field=config_app.fields.CustomPropertyValuesTextField(related_name='garden_values_text', to='config_app.propertyvaluetext', verbose_name='text values'),
        ),
    ]
