# Generated by Django 5.2 on 2026-01-22 08:31

import config_tables.admin
import django.db.models.deletion
import herbaria.models.specimen
import tools.global_request
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('individuals', '0003_add_and_alter_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Herbarium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='Name')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
            ],
            options={
                'verbose_name': 'Herbarium',
                'verbose_name_plural': 'Herbarium',
            },
            bases=(config_tables.admin.Configurable, models.Model),
        ),
        migrations.CreateModel(
            name='HerbariumSpecimen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_date', models.DateField(auto_now_add=True)),
                ('specimen_type', models.CharField(choices=[('plant_generative', 'Plant (generative)'), ('plant_vegetative', 'Plant (vegetative)'), ('blossoms', 'Blossoms'), ('leaves', 'Leaves'), ('fruits', 'Fruits')], db_index=True, default='plant_generative', max_length=32, verbose_name='Specimen type')),
                ('comment', models.TextField(blank=True, db_index=True, null=True, verbose_name='Comment')),
                ('collector', models.ForeignKey(default=tools.global_request.get_current_user, help_text='Collector', on_delete=django.db.models.deletion.CASCADE, related_name='herbarium_collectors', to=settings.AUTH_USER_MODEL, verbose_name='Legato')),
                ('herbarium', models.ForeignKey(default=herbaria.models.specimen.get_default_herbarium, on_delete=django.db.models.deletion.CASCADE, related_name='specimens', to='herbaria.herbarium')),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='herbarium_specimens', to='individuals.individual')),
            ],
            options={
                'verbose_name': 'Specimen',
                'verbose_name_plural': 'Specimens',
            },
            bases=(config_tables.admin.Configurable, models.Model),
        ),
    ]
