# Generated by Django 5.2 on 2026-03-04 11:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herbarium',
            name='date_created',
            field=models.DateField(auto_now_add=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='herbariumspecimen',
            name='collection_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Collection date'),
        ),
    ]
