# Generated by Django 5.2 on 2026-07-21 11:57

import config_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0004_customprops'),
        ('herbaria', '0002_alter_herbarium_specimen_collection_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='herbarium',
            name='custom_values_bool',
            field=config_app.fields.CustomPropertyValuesBoolField(related_name='herbarium_values_bool', to='config_app.propertyvaluebool', verbose_name='bool values'),
        ),
        migrations.AddField(
            model_name='herbarium',
            name='custom_values_text',
            field=config_app.fields.CustomPropertyValuesTextField(related_name='herbarium_values_text', to='config_app.propertyvaluetext', verbose_name='text values'),
        ),
        migrations.AddField(
            model_name='herbarium',
            name='custom_values_user',
            field=config_app.fields.CustomPropertyValuesUserField(related_name='herbarium_values_user', to='config_app.propertyvalueuser', verbose_name='user values'),
        ),
        migrations.AddField(
            model_name='herbariumspecimen',
            name='custom_values_bool',
            field=config_app.fields.CustomPropertyValuesBoolField(related_name='herbariumspecimen_values_bool', to='config_app.propertyvaluebool', verbose_name='bool values'),
        ),
        migrations.AddField(
            model_name='herbariumspecimen',
            name='custom_values_text',
            field=config_app.fields.CustomPropertyValuesTextField(related_name='herbariumspecimen_values_text', to='config_app.propertyvaluetext', verbose_name='text values'),
        ),
        migrations.AddField(
            model_name='herbariumspecimen',
            name='custom_values_user',
            field=config_app.fields.CustomPropertyValuesUserField(related_name='herbariumspecimen_values_user', to='config_app.propertyvalueuser', verbose_name='user values'),
        ),
    ]
