# Generated by Django 5.2 on 2026-07-21 11:57

from django.db import migrations, models
from django.conf import settings
import config_app.fields
import tools.global_request


def clear_creation_fields(apps, schema_editor):
    for Model in (
            apps.get_model('herbaria', 'Herbarium'),
            apps.get_model('herbaria', 'HerbariumSpecimen')
    ):
        Model.objects.all().update(created_date=None, modified_date=None)


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0004_customprops'),
        ('herbaria', '0002_alter_herbarium_specimen_collection_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='herbarium',
            name='custom_values_bool',
            field=config_app.fields.CustomPropertyValuesBoolField(related_name='herbarium_values_bool', to='config_app.propertyvaluebool', verbose_name='bool values'),
        ),
        migrations.AddField(
            model_name='herbarium',
            name='custom_values_text',
            field=config_app.fields.CustomPropertyValuesTextField(related_name='herbarium_values_text', to='config_app.propertyvaluetext', verbose_name='text values'),
        ),
        migrations.AddField(
            model_name='herbarium',
            name='custom_values_user',
            field=config_app.fields.CustomPropertyValuesUserField(related_name='herbarium_values_user', to='config_app.propertyvalueuser', verbose_name='user values'),
        ),
        migrations.AddField(
            model_name='herbarium',
            name='created_by',
            field=models.ForeignKey(null=True, blank=True, on_delete=models.deletion.CASCADE, related_name='herbarium_created_users', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='herbarium',
            name='created_date',
            field=models.DateField(null=True, blank=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='herbarium',
            name='modified_by',
            field=models.ForeignKey(null=True, blank=True, on_delete=models.deletion.CASCADE, related_name='herbarium_modified_users', to=settings.AUTH_USER_MODEL, verbose_name='modified by'),
        ),
        migrations.AddField(
            model_name='herbarium',
            name='modified_date',
            field=models.DateField(null=True, blank=True, verbose_name='modified at'),
        ),
        
        migrations.AddField(
            model_name='herbariumspecimen',
            name='custom_values_bool',
            field=config_app.fields.CustomPropertyValuesBoolField(related_name='herbariumspecimen_values_bool', to='config_app.propertyvaluebool', verbose_name='bool values'),
        ),
        migrations.AddField(
            model_name='herbariumspecimen',
            name='custom_values_text',
            field=config_app.fields.CustomPropertyValuesTextField(related_name='herbariumspecimen_values_text', to='config_app.propertyvaluetext', verbose_name='text values'),
        ),
        migrations.AddField(
            model_name='herbariumspecimen',
            name='custom_values_user',
            field=config_app.fields.CustomPropertyValuesUserField(related_name='herbariumspecimen_values_user', to='config_app.propertyvalueuser', verbose_name='user values'),
        ),
        migrations.AddField(
            model_name='herbariumspecimen',
            name='created_by',
            field=models.ForeignKey(null=True, blank=True, on_delete=models.deletion.CASCADE, related_name='herbariumspecimen_created_users', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='herbariumspecimen',
            name='created_date',
            field=models.DateField(null=True, blank=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='herbariumspecimen',
            name='modified_by',
            field=models.ForeignKey(null=True, blank=True, on_delete=models.deletion.CASCADE, related_name='herbariumspecimen_modified_users', to=settings.AUTH_USER_MODEL, verbose_name='modified by'),
        ),
        migrations.AddField(
            model_name='herbariumspecimen',
            name='modified_date',
            field=models.DateField(null=True, blank=True, verbose_name='modified at'),
        ),

        migrations.RunPython(clear_creation_fields, migrations.RunPython.noop),
    ]
