# Generated by Django 5.2 on 2026-09-16 10:26

import individuals.numbers
from django.db import migrations, models
from django.conf import settings


def assign_accession_numbers(apps, schema_editor):
    Model = apps.get_model("herbaria", "HerbariumSpecimen")
    for instance in Model.objects.all():
        instance.accession_number = individuals.numbers.get_new_herbarium_specimen_accession_number()
        instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ('herbaria', '0003_customprops'),
    ]

    operations = [
        migrations.AddField(
            model_name='herbariumspecimen',
            name='accession_number',
            field=models.CharField(
                blank=True,
                db_collation='natural_sort' if settings.IS_POSTGRES else None,
                db_index=True,
                default="",
                max_length=30,
                verbose_name='accession #',
            ),
        ),
        migrations.AlterField(
            model_name='herbariumspecimen',
            name='specimen_type',
            field=models.CharField(choices=[('plant_generative', 'Plant (generative) / pressed'), ('plant_vegetative', 'Plant (vegetative) / pressed'), ('blossoms', 'Blossoms / pressed'), ('leaves', 'Leaves / pressed'), ('fruits', 'Fruits / pressed'), ('seeds', 'Seeds / pressed'), ('plant_generative_liquid', 'Plant (generative) / liquid'), ('plant_vegetative_liquid', 'Plant (vegetative) / liquid'), ('blossoms_liquid', 'Blossoms / liquid'), ('leaves_liquid', 'Leaves / liquid'), ('fruits_liquid', 'Fruits / liquid'), ('seeds_liquid', 'Seeds / liquid'), ('plant_generative_3d', 'Plant (generative) / 3D dried'), ('plant_vegetative_3d', 'Plant (vegetative) / 3D dried'), ('blossoms_3d', 'Blossoms / 3D dried'), ('leaves_3d', 'Leaves / 3D dried'), ('fruits_3d', 'Fruits / 3D dried'), ('seeds_3d', 'Seeds / 3D dried')], db_index=True, default='plant_generative', max_length=32, verbose_name='Specimen type'),
        ),
        migrations.RunPython(assign_accession_numbers, reverse_code=migrations.RunPython.noop),
    ]
