# Generated by Django 5.2 on 2026-09-16 10:41

import individuals.numbers
from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('herbaria', '0004_herbariumspecimen_accession_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herbariumspecimen',
            name='accession_number',
            field=models.CharField(
                db_collation='natural_sort' if settings.IS_POSTGRES else None,
                db_index=True,
                default=individuals.numbers.get_new_herbarium_specimen_accession_number,
                max_length=30,
                unique=True,
                verbose_name='accession #'
            ),
        ),
    ]
